<a href="https://colab.research.google.com/github/gustavo-ifusp/prefeitura_smit_sp360/blob/main/9%20-%20CNES_base_estabelecimentos_de_saude.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**CNES - Cadastro Nacional de Estabelecimentos de Saúde - Dimensões**
**Link dos Dados de origem:**
http://cnes.datasus.gov.br/pages/downloads/arquivosBaseDados.jsp<br><br>

Responsável: Gustavo de Andrade - gustavo.andrade@prefeitura.sp.gov.br

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [ ]:
dados = pd.read_csv("cnes_sp.csv")

In [ ]:
dados

      COMPETÊNCIA  UF  ...  CNPJ DO ESTABELECIMENTO CNPJ DA MANTENEDORA
0         2021/10  SP  ...                      NaN                 NaN
1         2021/10  SP  ...       04.468.375/0001-31                 NaN
2         2021/10  SP  ...                      NaN                 NaN
3         2021/10  SP  ...                      NaN                 NaN
4         2021/10  SP  ...                      NaN                 NaN
...           ...  ..  ...                      ...                 ...
14317     2021/10  SP  ...       36.722.621/0001-26                 NaN
14318     2021/10  SP  ...       24.633.803/0002-22                 NaN
14319     2021/10  SP  ...       15.347.670/0002-37                 NaN
14320     2021/10  SP  ...       22.008.396/0001-56                 NaN
14321     2021/10  SP  ...       42.493.093/0001-83                 NaN

[14322 rows x 11 columns]

In [ ]:
dados.drop(columns =['COMPETÊNCIA','UF','CÓDIGO DO MUNICÍPIO','MUNICÍPIO','CNPJ DO ESTABELECIMENTO','CNPJ DA MANTENEDORA'], inplace = True)

In [ ]:
dados

          CNES  ...                   NATUREZA JURÍDICA
0      3881547  ...                  4000 PESSOA FISICA
1      3909050  ...  2062 SOCIEDADE EMPRESARIA LIMITADA
2      3918122  ...                  4000 PESSOA FISICA
3      5330998  ...                  4000 PESSOA FISICA
4      5626277  ...                  4000 PESSOA FISICA
...        ...  ...                                 ...
14317   760366  ...         2232 SOCIEDADE SIMPLES PURA
14318   760501  ...  2062 SOCIEDADE EMPRESARIA LIMITADA
14319   772003  ...     2240 SOCIEDADE SIMPLES LIMITADA
14320   811769  ...  2062 SOCIEDADE EMPRESARIA LIMITADA
14321   835471  ...  2062 SOCIEDADE EMPRESARIA LIMITADA

[14322 rows x 5 columns]

#**cnes_dim_tipo_estabelecimento**

In [ ]:
tipo = pd.DataFrame()
tipo['total'] = dados.groupby(['TIPO DO ESTABELECIMENTO']).size().sort_values(ascending=False)

In [ ]:
tipo

                                                    total
TIPO DO ESTABELECIMENTO
22 CONSULTORIO ISOLADO                               8726
36 CLINICA/CENTRO DE ESPECIALIDADE                   2903
39 UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT IS...    795
02 CENTRO DE SAUDE/UNIDADE BASICA                     516
04 POLICLINICA                                        280
43 FARMACIA                                           226
42 UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA ARE...    180
05 HOSPITAL GERAL                                     149
70 CENTRO DE ATENCAO PSICOSSOCIAL                      98
77 SERVICO DE ATENCAO DOMICILIAR ISOLADO(HOME C...     70
07 HOSPITAL ESPECIALIZADO                              54
62 HOSPITAL/DIA - ISOLADO                              49
73 PRONTO ATENDIMENTO                                  41
40 UNIDADE MOVEL TERRESTRE                             32
69 CENTRO DE ATENCAO HEMOTERAPIA E OU HEMATOLOGICA     32
85 CENTRO DE IMUNIZACAO                                31
50 UNIDADE DE VIGILANCIA EM SAUDE                      29
84 CENTRAL DE ABASTECIMENTO                            18
01 POSTO DE SAUDE                                      15
68 CENTRAL DE GESTAO EM SAUDE                          15
20 PRONTO SOCORRO GERAL                                15
75 TELESSAUDE                                          13
81 CENTRAL DE REGULACAO DO ACESSO                       9
80 LABORATORIO DE SAUDE PUBLICA                         7
82 CENTRAL DE NOTIFICACAO,CAPTACAO E DISTRIB DE...      6
61 CENTRO DE PARTO NORMAL - ISOLADO                     2
60 COOPERATIVA OU EMPRESA DE CESSAO DE TRABALHA...      2
72 UNIDADE DE ATENCAO A SAUDE INDIGENA                  2
83 POLO DE PREVENCAO DE DOENCAS E AGRAVOS E PRO...      1
64 CENTRAL DE REGULACAO DE SERVICOS DE SAUDE            1
15 UNIDADE MISTA                                        1
21 PRONTO SOCORRO ESPECIALIZADO                         1
79 OFICINA ORTOPEDICA                                   1
67 LABORATORIO CENTRAL DE SAUDE PUBLICA LACEN           1
76 CENTRAL DE REGULACAO MEDICA DAS URGENCIAS            1

In [ ]:
dados2 = pd.read_csv("tbTipoUnidade202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados2

    CO_TIPO_UNIDADE                                    DS_TIPO_UNIDADE
0                69    CENTRO DE ATENCAO HEMOTERAPIA E OU HEMATOLOGICA
1                70                     CENTRO DE ATENCAO PSICOSSOCIAL
2                71                 CENTRO DE APOIO A SAUDE DA FAMILIA
3                72                UNIDADE DE ATENCAO A SAUDE INDIGENA
4                 1                                     POSTO DE SAUDE
5                 2                     CENTRO DE SAUDE/UNIDADE BASICA
6                 4                                        POLICLINICA
7                22                                CONSULTORIO ISOLADO
8                40                            UNIDADE MOVEL TERRESTRE
9                42  UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA ...
10               32                              UNIDADE MOVEL FLUVIAL
11               36                    CLINICA/CENTRO DE ESPECIALIDADE
12               64          CENTRAL DE REGULACAO DE SERVICOS DE SAUDE
13               43                                           FARMACIA
14               39  UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOL...
15               61                   CENTRO DE PARTO NORMAL - ISOLADO
16               62                             HOSPITAL/DIA - ISOLADO
17               15                                      UNIDADE MISTA
18               20                               PRONTO SOCORRO GERAL
19               21                       PRONTO SOCORRO ESPECIALIZADO
20                5                                     HOSPITAL GERAL
21                7                             HOSPITAL ESPECIALIZADO
22               60  COOPERATIVA OU EMPRESA DE CESSAO DE TRABALHADO...
23               50                     UNIDADE DE VIGILANCIA EM SAUDE
24               67         LABORATORIO CENTRAL DE SAUDE PUBLICA LACEN
25               68                         CENTRAL DE GESTAO EM SAUDE
26               73                                 PRONTO ATENDIMENTO
27               82  CENTRAL DE NOTIFICACAO,CAPTACAO E DISTRIB DE O...
28               75                                         TELESSAUDE
29               80                       LABORATORIO DE SAUDE PUBLICA
30               78           UNIDADE DE ATENCAO EM REGIME RESIDENCIAL
31               74                             POLO ACADEMIA DA SAUDE
32               84                           CENTRAL DE ABASTECIMENTO
33               85                               CENTRO DE IMUNIZACAO
34               83  POLO DE PREVENCAO DE DOENCAS E AGRAVOS E PROMO...
35               77   SERVICO DE ATENCAO DOMICILIAR ISOLADO(HOME CARE)
36               76          CENTRAL DE REGULACAO MEDICA DAS URGENCIAS
37               79                                 OFICINA ORTOPEDICA
38               81                     CENTRAL DE REGULACAO DO ACESSO

In [ ]:
cnes_dim_tipo_unidade = pd.DataFrame()
cnes_dim_tipo_unidade['tipo_unidade'] = dados2['DS_TIPO_UNIDADE']
cnes_dim_tipo_unidade['id_unidade'] = dados2['CO_TIPO_UNIDADE']

In [ ]:
cnes_dim_tipo_unidade = cnes_dim_tipo_unidade.sort_values(by=['id_unidade'], ascending=True)

In [ ]:
cnes_dim_tipo_estabelecimento

                                 tipo_estabelecimento  id_estabelecimento
4                                      POSTO DE SAUDE                   1
5                      CENTRO DE SAUDE/UNIDADE BASICA                   2
6                                         POLICLINICA                   4
20                                     HOSPITAL GERAL                   5
21                             HOSPITAL ESPECIALIZADO                   7
17                                      UNIDADE MISTA                  15
18                               PRONTO SOCORRO GERAL                  20
19                       PRONTO SOCORRO ESPECIALIZADO                  21
7                                 CONSULTORIO ISOLADO                  22
10                              UNIDADE MOVEL FLUVIAL                  32
11                    CLINICA/CENTRO DE ESPECIALIDADE                  36
14  UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOL...                  39
8                             UNIDADE MOVEL TERRESTRE                  40
9   UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA ...                  42
13                                           FARMACIA                  43
23                     UNIDADE DE VIGILANCIA EM SAUDE                  50
22  COOPERATIVA OU EMPRESA DE CESSAO DE TRABALHADO...                  60
15                   CENTRO DE PARTO NORMAL - ISOLADO                  61
16                             HOSPITAL/DIA - ISOLADO                  62
12          CENTRAL DE REGULACAO DE SERVICOS DE SAUDE                  64
24         LABORATORIO CENTRAL DE SAUDE PUBLICA LACEN                  67
25                         CENTRAL DE GESTAO EM SAUDE                  68
0     CENTRO DE ATENCAO HEMOTERAPIA E OU HEMATOLOGICA                  69
1                      CENTRO DE ATENCAO PSICOSSOCIAL                  70
2                  CENTRO DE APOIO A SAUDE DA FAMILIA                  71
3                 UNIDADE DE ATENCAO A SAUDE INDIGENA                  72
26                                 PRONTO ATENDIMENTO                  73
31                             POLO ACADEMIA DA SAUDE                  74
28                                         TELESSAUDE                  75
36          CENTRAL DE REGULACAO MEDICA DAS URGENCIAS                  76
35   SERVICO DE ATENCAO DOMICILIAR ISOLADO(HOME CARE)                  77
30           UNIDADE DE ATENCAO EM REGIME RESIDENCIAL                  78
37                                 OFICINA ORTOPEDICA                  79
29                       LABORATORIO DE SAUDE PUBLICA                  80
38                     CENTRAL DE REGULACAO DO ACESSO                  81
27  CENTRAL DE NOTIFICACAO,CAPTACAO E DISTRIB DE O...                  82
34  POLO DE PREVENCAO DE DOENCAS E AGRAVOS E PROMO...                  83
32                           CENTRAL DE ABASTECIMENTO                  84
33                               CENTRO DE IMUNIZACAO                  85

In [ ]:
cnes_dim_tipo_unidade.to_csv(r'cnes_dim_tipo_unidade.csv', index = False)

#**cnes_dim_tipo_estabelecimento**

In [ ]:
dados4 = pd.read_csv("tbTipoEstabelecimento202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados4

    CO_TIPO_ESTABELECIMENTO  ... DS_CONCEITO_TIPO
0                         0  ...              NaN
1                         1  ...              NaN
2                         2  ...              NaN
3                         3  ...              NaN
4                         4  ...              NaN
5                         5  ...              NaN
6                         6  ...              NaN
7                         7  ...              NaN
8                         8  ...              NaN
9                         9  ...              NaN
10                       10  ...              NaN
11                       11  ...              NaN
12                       12  ...              NaN
13                       13  ...              NaN
14                       14  ...              NaN
15                       15  ...              NaN
16                       16  ...              NaN
17                       17  ...              NaN
18                       18  ...              NaN
19                       19  ...              NaN
20                       20  ...              NaN
21                       21  ...              NaN
22                       22  ...              NaN
23                       23  ...              NaN
24                       24  ...              NaN
25                       25  ...              NaN

[26 rows x 3 columns]

In [ ]:
cnes_dim_tipo_estabelecimento = pd.DataFrame()
cnes_dim_tipo_estabelecimento['tipo_estabelecimento'] = dados4['DS_TIPO_ESTABELECIMENTO']
cnes_dim_tipo_estabelecimento['id_tipo_estabelecimento'] = dados4['CO_TIPO_ESTABELECIMENTO']

In [ ]:
cnes_dim_tipo_estabelecimento = cnes_dim_tipo_estabelecimento.sort_values(by=['id_tipo_estabelecimento'], ascending=True)

In [ ]:
cnes_dim_tipo_estabelecimento

                                 tipo_estabelecimento  id_tipo_estabelecimento
0                                              OUTROS                        0
1                             UNIDADE BASICA DE SAUDE                        1
2                          CENTRAL DE GESTAO EM SAUDE                        2
3                                CENTRAL DE REGULACAO                        3
4                            CENTRAL DE ABASTECIMENTO                        4
5                              CENTRAL DE TRANSPLANTE                        5
6                                            HOSPITAL                        6
7   CENTRO DE ASSISTENCIA OBSTETRICA E NEONATAL NO...                        7
8                                  PRONTO ATENDIMENTO                        8
9                                            FARMACIA                        9
10  UNIDADE DE ATENCAO HEMATOLOGICA E/OU HEMOTERAPICA                       10
11                               NUCLEO DE TELESSAUDE                       11
12                      UNIDADE DE ATENCAO DOMICILIAR                       12
13  POLO DE PREVENCAO DE DOENCAS E AGRAVOS E PROMO...                       13
14                             CASAS DE APOIO A SAUDE                       14
15                            UNIDADE DE REABILITACAO                       15
16                                        AMBULATORIO                       16
17                    UNIDADE DE ATENCAO PSICOSSOCIAL                       17
18                       UNIDADE DE APOIO DIAGNOSTICO                       18
19                      UNIDADE DE TERAPIAS ESPECIAIS                       19
20                    LABORATORIO DE PROTESE DENTARIA                       20
21                  UNIDADE DE VIGILANCIA DE ZOONOSES                       21
22                       LABORATORIO DE SAUDE PUBLICA                       22
23       CENTRO DE REFERENCIA EM SAUDE DO TRABALHADOR                       23
24                    SERVICO DE VERIFICACAO DE OBITO                       24
25                               CENTRO DE IMUNIZACAO                       25

In [ ]:
cnes_dim_tipo_estabelecimento.to_csv(r'cnes_dim_tipo_estabelecimento.csv', index = False)

#**cnes_dim_servico_referenciado**

In [ ]:
dados3 = pd.read_csv("tbTipoServicoReferenciado202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados3

    CO_TIPO_SERVICO_REFERENCIADO  ...                       DS_TIPO_SERVICO_REFERENCIADO
0                              1  ...                          HOSPITAL PARA TRANSPLANTE
1                              3  ...                       HOSPITAL GERAL ESPECIALIZADO
2                              5  ...                     SERVICO DE LABORATORIO CLINICO
3                              7  ...  MANUTENCAO DOS EQUIPAMENTOS DE TRATAMENTO DE AGUA
4                              9  ...                           SERVICOS DE RADIOTERAPIA
5                             11  ...              SERVICO DE TOMOGRAFIA COMPUTADORIZADA
6                             13  ...           SERVICO DE ANATOMIA PATOLOGICA/CITOLOGIA
7                             15  ...                                   ULTRA-SONOGRAFIA
8                             17  ...                                 SERVICO DE PROTESE
9                             19  ...                              CENTRO DE ONCOLOGIA I
10                            21  ...                            CENTRO DE ONCOLOGIA III
11                            23  ...                                HEMOCENTRO REGIONAL
12                            25  ...                                 CENTRAL SOROLOGICA
13                            27  ...                        SERVICO DE ULTRA-SONOGRAFIA
14                            29  ...                  SERVICO DE NEFROLOGIA PARA HSBSG+
15                             2  ...                LABORATORIO DE HISTOCOMPATIBILIDADE
16                             4  ...           SERVICO DE ANATOMIA PATOLOGICA/CITOLOGIA
17                             6  ...              MANUTENCAO DE EQUIPAMENTOS DE DIALISE
18                             8  ...                   LABORATORIO PARA ANALISE DE AGUA
19                            10  ...                LABORATORIO DE HISTOCOMPATIBILIDADE
20                            12  ...                              RESSONANCIA MAGNETICA
21                            14  ...                                  PATOLOGIA CLINICA
22                            16  ...                        SERVICO DE MEDICINA NUCLEAR
23                            18  ...                         MANUTENCAO DE EQUIPAMENTOS
24                            20  ...                             CENTRO DE ONCOLOGIA II
25                            22  ...                             HEMOCENTRO COORDENADOR
26                            24  ...                              NUCLEO DE HEMOTERAPIA
27                            26  ...                              SERVICO DE RADIOLOGIA
28                            28  ...                     SERVICO DE NEFROLOGIA PARA DPI
29                            30  ...                       SERVICO DE CIRURGIA VASCULAR

[30 rows x 3 columns]

In [ ]:
cnes_dim_servico_referenciado = pd.DataFrame()
cnes_dim_servico_referenciado['tipo_servico_referenciado'] = dados3['DS_TIPO_SERVICO_REFERENCIADO']
cnes_dim_servico_referenciado['id_estabelecimento'] = dados3['CO_TIPO_SERVICO_REFERENCIADO']

In [ ]:
cnes_dim_servico_referenciado = cnes_dim_servico_referenciado.sort_values(by=['id_estabelecimento'], ascending=True)

In [ ]:
cnes_dim_servico_referenciado

                            tipo_servico_referenciado  id_estabelecimento
0                           HOSPITAL PARA TRANSPLANTE                   1
15                LABORATORIO DE HISTOCOMPATIBILIDADE                   2
1                        HOSPITAL GERAL ESPECIALIZADO                   3
16           SERVICO DE ANATOMIA PATOLOGICA/CITOLOGIA                   4
2                      SERVICO DE LABORATORIO CLINICO                   5
17              MANUTENCAO DE EQUIPAMENTOS DE DIALISE                   6
3   MANUTENCAO DOS EQUIPAMENTOS DE TRATAMENTO DE AGUA                   7
18                   LABORATORIO PARA ANALISE DE AGUA                   8
4                            SERVICOS DE RADIOTERAPIA                   9
19                LABORATORIO DE HISTOCOMPATIBILIDADE                  10
5               SERVICO DE TOMOGRAFIA COMPUTADORIZADA                  11
20                              RESSONANCIA MAGNETICA                  12
6            SERVICO DE ANATOMIA PATOLOGICA/CITOLOGIA                  13
21                                  PATOLOGIA CLINICA                  14
7                                    ULTRA-SONOGRAFIA                  15
22                        SERVICO DE MEDICINA NUCLEAR                  16
8                                  SERVICO DE PROTESE                  17
23                         MANUTENCAO DE EQUIPAMENTOS                  18
9                               CENTRO DE ONCOLOGIA I                  19
24                             CENTRO DE ONCOLOGIA II                  20
10                            CENTRO DE ONCOLOGIA III                  21
25                             HEMOCENTRO COORDENADOR                  22
11                                HEMOCENTRO REGIONAL                  23
26                              NUCLEO DE HEMOTERAPIA                  24
12                                 CENTRAL SOROLOGICA                  25
27                              SERVICO DE RADIOLOGIA                  26
13                        SERVICO DE ULTRA-SONOGRAFIA                  27
28                     SERVICO DE NEFROLOGIA PARA DPI                  28
14                  SERVICO DE NEFROLOGIA PARA HSBSG+                  29
29                       SERVICO DE CIRURGIA VASCULAR                  30

In [ ]:
cnes_dim_servico_referenciado.to_csv(r'cnes_dim_servico_referenciado.csv', index = False)

#**cnes_dim_servico_especializado**

In [ ]:
dados5 = pd.read_csv("tbServicoEspecializado202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados5

    CO_SERVICO_ESPECIALIZADO                         DS_SERVICO_ESPECIALIZADO
0                        100         ATENCAO A SAUDE NO SISTEMA PENITENCIARIO
1                        101                   ESTRATEGIA DE SAUDE DA FAMILIA
2                        102      ESTRATEGIA DE AGENTES COMUNITARIOS DE SAUDE
3                        103        SERVICO DE ATENDIMENTO MOVEL DE URGENCIAS
4                        104  REGULACAO DO ACESSO A ACOES E SERVICOS DE SAUDE
..                       ...                                              ...
66                       168              ATENCAO A PESSOAS COM DOENCAS RARAS
67                       169                              ATENCAO EM UROLOGIA
68                       170                              COMISSOES E COMITES
69                       173                     LOGISTICA DE IMUNOBIOLOGICOS
70                       174                                       IMUNIZACAO

[71 rows x 2 columns]

In [ ]:
cnes_dim_servico_especializado = pd.DataFrame()
cnes_dim_servico_especializado['servico_especializado'] = dados5['DS_SERVICO_ESPECIALIZADO']
cnes_dim_servico_especializado['id_servico_especializado'] = dados5['CO_SERVICO_ESPECIALIZADO']

In [ ]:
cnes_dim_servico_especializado = cnes_dim_servico_especializado.sort_values(by=['id_servico_especializado'], ascending=True)

In [ ]:
cnes_dim_servico_especializado

                              servico_especializado  id_servico_especializado
0          ATENCAO A SAUDE NO SISTEMA PENITENCIARIO                       100
1                    ESTRATEGIA DE SAUDE DA FAMILIA                       101
2       ESTRATEGIA DE AGENTES COMUNITARIOS DE SAUDE                       102
3         SERVICO DE ATENDIMENTO MOVEL DE URGENCIAS                       103
4   REGULACAO DO ACESSO A ACOES E SERVICOS DE SAUDE                       104
..                                              ...                       ...
66              ATENCAO A PESSOAS COM DOENCAS RARAS                       168
67                              ATENCAO EM UROLOGIA                       169
68                              COMISSOES E COMITES                       170
69                     LOGISTICA DE IMUNOBIOLOGICOS                       173
70                                       IMUNIZACAO                       174

[71 rows x 2 columns]

In [ ]:
cnes_dim_servico_especializado.to_csv(r'cnes_dim_servico_especializado.csv', index = False)

#**cnes_dim_instalacao_fisica**

In [ ]:
dados6 = pd.read_csv("tbTipoInstalacaoFisica202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados6

   CO_TIPO_INSTALACAO_FISICA DS_TIPO_INSTALACAO_FISICA
0                          0     URGENCIA E EMERGENCIA
1                          1               AMBULATORIO
2                          2                HOSPITALAR
3                          3            INFRAESTRUTURA

In [ ]:
cnes_dim_instalacao_fisica = pd.DataFrame()
cnes_dim_instalacao_fisica['tipo_intalacao_fisica'] = dados6['DS_TIPO_INSTALACAO_FISICA']
cnes_dim_instalacao_fisica['id_tipo_intalacao_fisica'] = dados6['CO_TIPO_INSTALACAO_FISICA']

In [ ]:
cnes_dim_instalacao_fisica = cnes_dim_instalacao_fisica.sort_values(by=['id_tipo_intalacao_fisica'], ascending=True)

In [ ]:
cnes_dim_instalacao_fisica

   tipo_intalacao_fisica  id_tipo_intalacao_fisica
0  URGENCIA E EMERGENCIA                         0
1            AMBULATORIO                         1
2             HOSPITALAR                         2
3         INFRAESTRUTURA                         3

In [ ]:
cnes_dim_instalacao_fisica.to_csv(r'cnes_dim_instalacao_fisica.csv', index = False)

#**cnes_dim_tipo_intalacao_fisica**

In [ ]:
dados7 = pd.read_csv("tbInstalFisicaParaAssist202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados7

    CO_INSTALACAO  ...  TP_INSTALACAO
0               1  ...              0
1               2  ...              0
2               3  ...              0
3               4  ...              0
4               5  ...              0
5               6  ...              0
6               7  ...              0
7               8  ...              0
8               9  ...              0
9              10  ...              0
10             11  ...              0
11             12  ...              0
12             13  ...              0
13             14  ...              0
14             15  ...              1
15             16  ...              1
16             17  ...              1
17             18  ...              1
18             19  ...              1
19             20  ...              1
20             21  ...              1
21             22  ...              1
22             23  ...              1
23             24  ...              1
24             25  ...              1
25             26  ...              1
26             27  ...              1
27             28  ...              1
28             29  ...              1
29             30  ...              1
30             31  ...              2
31             32  ...              2
32             33  ...              2
33             34  ...              2
34             35  ...              2
35             36  ...              2
36             37  ...              2
37             38  ...              2
38             39  ...              2
39             40  ...              2
40             41  ...              0
41             42  ...              0
42             44  ...              3
43             45  ...              3
44             46  ...              3
45             47  ...              3
46             48  ...              3
47             49  ...              3
48             43  ...              2

[49 rows x 4 columns]

In [ ]:
cnes_dim_tipo_intalacao_fisica = pd.DataFrame()
cnes_dim_tipo_intalacao_fisica['tipo_intalacao_fisica'] = dados7['DS_INSTALACAO']
cnes_dim_tipo_intalacao_fisica['id_tipo_intalacao_fisica'] = dados7['CO_INSTALACAO']

In [ ]:
cnes_dim_tipo_intalacao_fisica = cnes_dim_tipo_intalacao_fisica.sort_values(by=['id_tipo_intalacao_fisica'], ascending=True)

In [ ]:
cnes_dim_tipo_intalacao_fisica

                                tipo_intalacao_fisica  id_tipo_intalacao_fisica
0                      SALA DE ATENDIMENTO PEDIATRICO                         1
1                        SALA DE ATENDIMENTO FEMININO                         2
2                       SALA DE ATENDIMENTO MASCULINO                         3
3                  SALA DE ATENDIMENTO INDIFERENCIADO                         4
4                SALA REPOUSO/OBSERVACAO - PEDIATRICA                         5
5                  SALA REPOUSO/OBSERVACAO - FEMININO                         6
6                 SALA REPOUSO/OBSERVACAO - MASCULINO                         7
7            SALA REPOUSO/OBSERVACAO - INDIFERENCIADO                         8
8                                         ODONTOLOGIA                         9
9                                SALA DE HIGIENIZACAO                        10
10                                      SALA DE GESSO                        11
11                                   SALA DE CURATIVO                        12
12                              SALA PEQUENA CIRURGIA                        13
13                               CONSULTORIOS MEDICOS                        14
14                                   CLINICAS BASICAS                        15
15                            CLINICAS ESPECIALIZADAS                        16
16                            CLINICAS INDIFERENCIADO                        17
17                    OUTROS CONSULTORIOS NAO MEDICOS                        18
18                 SALA REPOUSO/OBSERVACAO - FEMININO                        19
19                SALA REPOUSO/OBSERVACAO - MASCULINO                        20
20               SALA REPOUSO/OBSERVACAO - PEDIATRICA                        21
21        SALA DE REPOUSO/OBSERVACAO - INDIFERENCIADO                        22
22                                        ODONTOLOGIA                        23
23                           SALA DE PEQUENA CIRURGIA                        24
24                      SALA DE ENFERMAGEM (SERVICOS)                        25
25                                 SALA DE IMUNIZACAO                        26
26                                SALA DE NEBULIZACAO                        27
27                                      SALA DE GESSO                        28
28                                   SALA DE CURATIVO                        29
29                      SALA DE CIRURGIA AMBULATORIAL                        30
30                                   SALA DE CIRURGIA                        31
31                                SALA DE RECUPERACAO                        32
32                      SALA DE CIRURGIA AMBULATORIAL                        33
33                                  SALA DE PRE-PARTO                        34
34                               SALA DE PARTO NORMAL                        35
35                                  SALA DE CURETAGEM                        36
36                                   SALA DE CIRURGIA                        37
37                                   LEITOS RN NORMAL                        38
38                               LEITOS RN PATOLOGICO                        39
39                      LEITOS DE ALOJAMENTO CONJUNTO                        40
40  SAlA DE ATENDIMENTO A PACIENTE CRITICO/SALA DE...                        41
41     SALA DE ACOLHIMENTO COM CLASSIFICACAO DE RISCO                        42
48                                      BRINQUEDOTECA                        43
42                        SALA DE RECEPCAO E INSPECAO                        44
43                               SALA DE DISTRIBUICAO                        45
44                   SALA PARA ARMAZENAGEM E CONTROLE                        46
45                                       ALMOXARIFADO                        47
46  SALA PARA EQUIP DE GERACAO DE ENERGIA ELETRICA...                        48
47                          CASA DE BOMBAS / MAQUINAS                        49

In [ ]:
cnes_dim_tipo_intalacao_fisica.to_csv(r'cnes_dim_tipo_intalacao_fisica.csv', index = False)

#**cnes_dim_equipamentos**

In [ ]:
dados8 = pd.read_csv("tbEquipamento202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados8

    CO_EQUIPAMENTO  ...                                     DS_EQUIPAMENTO
0               80  ...                                Equipo Odontologico
1               81  ...                            Compressor Odontologico
2               82  ...                                  Fotopolimerizador
3               83  ...                             Caneta de Alta Rotacao
4               84  ...                            Caneta de Baixa Rotacao
..             ...  ...                                                ...
95              67  ...                           CAMINHAO BAU REFRIGERADO
96              68  ...  EMBARCACAO PARA TRANSPORTE COM MOTOR POPA (ATE...
97              69  ...                                       EMPILHADEIRA
98              70  ...                   VEICULO UTILITARIO (TIPO FURGAO)
99              79  ...          VEICULO PICK-UP CABINE DUPLA 4X4 (DIESEL)

[100 rows x 3 columns]

In [ ]:
cnes_dim_equipamentos = pd.DataFrame()
cnes_dim_equipamentos['tipo_equipamentos'] = dados8['DS_EQUIPAMENTO']
cnes_dim_equipamentos['id_equipamentos'] = dados8['CO_EQUIPAMENTO']
cnes_dim_equipamentos['id_tipo_equipamentos'] = dados8['CO_TIPO_EQUIPAMENTO']

In [ ]:
cnes_dim_equipamentos = cnes_dim_equipamentos.sort_values(by=['id_equipamentos'], ascending=True)

In [ ]:
cnes_dim_equipamentos

                          tipo_equipamentos  ...  id_tipo_equipamentos
7                               Gama Camara  ...                     1
8             Mamografo com Comando Simples  ...                     1
9                Mamografo com Estereotaxia  ...                     1
10                        Raio X ate 100 mA  ...                     1
11                   Raio X de 100 a 500 mA  ...                     1
..                                      ...  ...                   ...
75                          CABINE ACUSTICA  ...                     8
76                   SISTEMA DE CAMPO LIVRE  ...                     8
77  SISTEMA COMPLETO DE REFORÇO VISUAL(VRA)  ...                     8
78                        GANHO DE INSERCAO  ...                     8
79                                   HI-PRO  ...                     8

[100 rows x 3 columns]

In [ ]:
cnes_dim_equipamentos.to_csv(r'cnes_dim_equipamentos.csv', index = False)

#**cnes_dim_classificacao_servico**

In [ ]:
dados9 = pd.read_csv("tbClassificacaoServico202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados9

     CO_CLASSIFICACAO_SERVICO  ...                   DS_CLASSIFICACAO_SERVICO
0                           2  ...                  MEDICINA NUCLEAR IN VITRO
1                           3  ...  MEDICINA NUCLEAR IN VIVO POR TELEMEDICINA
2                           1  ...      ATENCAO BASICA A POPULACOES INDIGENAS
3                           9  ...       SUBSTITUICAOTROCA EM ORTESESPROTESES
4                          10  ...                           OPM EM QUEIMADOS
..                        ...  ...                                        ...
419                        10  ...            EXAME VIDEOELETROENCEFALOGRAFIA
420                        11  ...                        POTENCIAIS EVOCADOS
421                        12  ...       POTENCIAIS EVOCADOS POR TELEMEDICINA
422                         7  ...                         OPM EM ODONTOLOGIA
423                         8  ...                     OPM BUCO MAXILO FACIAL

[424 rows x 3 columns]

In [ ]:
cnes_dim_classificacao_servico = pd.DataFrame()
cnes_dim_classificacao_servico['classificacao_servico'] = dados9['DS_CLASSIFICACAO_SERVICO']
cnes_dim_classificacao_servico['id_classificacao_servico'] = dados9['CO_CLASSIFICACAO_SERVICO']
cnes_dim_classificacao_servico['id_servico_especializado'] = dados9['CO_SERVICO_ESPECIALIZADO']

In [ ]:
cnes_dim_classificacao_servico = cnes_dim_classificacao_servico.sort_values(by=['id_classificacao_servico'], ascending=True)

In [ ]:
cnes_dim_classificacao_servico

                  classificacao_servico  ...  id_servico_especializado
27                    SEM CLASSIFICACAO  ...                       128
396                   SEM CLASSIFICACAO  ...                       121
115                   SEM CLASSIFICACAO  ...                       143
87                    SEM CLASSIFICACAO  ...                       140
120                   SEM CLASSIFICACAO  ...                       145
..                                  ...  ...                       ...
103  PRONTO SOCORRO TRAUMATO ORTOPEDICO  ...                       140
104         PRONTO SOCORRO ODONTOLOGICO  ...                       140
241                            DIVERSOS  ...                       166
105        PRONTO SOCORRO OFTALMOLOGICO  ...                       140
106        PRONTO SOCORRO GERAL/CLINICO  ...                       140

[424 rows x 3 columns]

In [ ]:
cnes_dim_classificacao_servico.to_csv(r'cnes_dim_classificacao_servico.csv', index = False)

#**cnes_dim_atendimento_prestado**

In [ ]:
dados10 = pd.read_csv("tbAtendimentoPrestado202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados10

   CO_ATENDIMENTO_PRESTADO DS_ATENDIMENTO_PRESTADO
0                        1              INTERNACAO
1                        2            AMBULATORIAL
2                        3                    SADT
3                        4                URGENCIA
4                        5                  OUTROS
5                        6     VIGILANCIA EM SAUDE
6                        7               REGULACAO

In [ ]:
cnes_dim_atendimento_prestado = pd.DataFrame()
cnes_dim_atendimento_prestado['atendimento_prestado'] = dados10['DS_ATENDIMENTO_PRESTADO']
cnes_dim_atendimento_prestado['id_atendimento_prestado'] = dados10['CO_ATENDIMENTO_PRESTADO']

In [ ]:
cnes_dim_atendimento_prestado = cnes_dim_atendimento_prestado.sort_values(by=['id_atendimento_prestado'], ascending=True)

In [ ]:
cnes_dim_atendimento_prestado

  atendimento_prestado  id_atendimento_prestado
0           INTERNACAO                        1
1         AMBULATORIAL                        2
2                 SADT                        3
3             URGENCIA                        4
4               OUTROS                        5
5  VIGILANCIA EM SAUDE                        6
6            REGULACAO                        7

In [ ]:
cnes_dim_atendimento_prestado.to_csv(r'cnes_dim_atendimento_prestado.csv', index = False)

#**cnes_dim_leitos**

In [ ]:
dados11 = pd.read_csv("tbLeito202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados11

    CO_LEITO                                           DS_LEITO  TP_LEITO
0          1                                 BUCO MAXILO FACIAL         1
1          2                                        CARDIOLOGIA         1
2          3                                     CIRURGIA GERAL         1
3          4                                     ENDOCRINOLOGIA         1
4          5                                  GASTROENTEROLOGIA         1
..       ...                                                ...       ...
64        94      UNIDADE DE CUIDADOS INTERMEDIARIOS PEDIATRICO         3
65        95          UNIDADE DE CUIDADOS INTERMEDIARIOS ADULTO         3
66        51  UTI II ADULTO-SINDROME RESP. AGUDA GRAVE (SRAG...         3
67        52  UTI II PEDIATRICA-SINDROME RESP. AGUDA GRAVE (...         3
68        96           SUPORTE VENTILATÓRIO PULMONAR - COVID-19         3

[69 rows x 3 columns]

In [ ]:
cnes_dim_leitos = pd.DataFrame()
cnes_dim_leitos['classificacao_servico'] = dados11['DS_LEITO']
cnes_dim_leitos['id_leitos'] = dados11['CO_LEITO']
cnes_dim_leitos['id_tipos_leitos'] = dados11['TP_LEITO']

In [ ]:
cnes_dim_leitos = cnes_dim_leitos.sort_values(by=['id_leitos'], ascending=True)

In [ ]:
cnes_dim_leitos

                                classificacao_servico  ...  id_tipos_leitos
0                                  BUCO MAXILO FACIAL  ...                1
1                                         CARDIOLOGIA  ...                1
2                                      CIRURGIA GERAL  ...                1
3                                      ENDOCRINOLOGIA  ...                1
4                                   GASTROENTEROLOGIA  ...                1
..                                                ...  ...              ...
62  UNIDADE DE CUIDADOS INTERMEDIARIOS NEONATAL CO...  ...                3
63  UNIDADE DE CUIDADOS INTERMEDIARIOS NEONATAL CA...  ...                3
64      UNIDADE DE CUIDADOS INTERMEDIARIOS PEDIATRICO  ...                3
65          UNIDADE DE CUIDADOS INTERMEDIARIOS ADULTO  ...                3
68           SUPORTE VENTILATÓRIO PULMONAR - COVID-19  ...                3

[69 rows x 3 columns]

In [ ]:
cnes_dim_leitos.to_csv(r'cnes_dim_leitos.csv', index = False)

#**cnes_dim_convenio**

In [ ]:
dados12 = pd.read_csv("tbConvenio202108.csv", sep = ';', header = 0, decimal = ',', parse_dates=True, encoding='utf-8')

In [ ]:
dados12

   CO_CONVENIO              DS_CONVENIO
0            1                      SUS
1            2               PARTICULAR
2            3   PLANO / SEGURO PROPRIO
3            4  PLANO / SEGURO TERCEIRO
4            5   PLANO DE SAUDE PUBLICO
5            6   PLANO DE SAUDE PRIVADO
6            7               GRATUIDADE

In [ ]:
cnes_dim_convenio = pd.DataFrame()
cnes_dim_convenio['convenios'] = dados12['DS_CONVENIO']
cnes_dim_convenio['id_convenios'] = dados12['CO_CONVENIO']

In [ ]:
cnes_dim_convenio = cnes_dim_convenio.sort_values(by=['id_convenios'], ascending=True)

In [ ]:
cnes_dim_convenio

                 convenios  id_convenios
0                      SUS             1
1               PARTICULAR             2
2   PLANO / SEGURO PROPRIO             3
3  PLANO / SEGURO TERCEIRO             4
4   PLANO DE SAUDE PUBLICO             5
5   PLANO DE SAUDE PRIVADO             6
6               GRATUIDADE             7

In [ ]:
cnes_dim_convenio.to_csv(r'cnes_dim_convenio.csv', index = False)

#**Gestão Sigla**

In [ ]:
tipo3 = pd.DataFrame()
tipo3['total'] = dados.groupby(['GESTÃO SIGLA']).size().sort_values(ascending=False)

In [ ]:
tipo3

              total
GESTÃO SIGLA
M             14223
E                99

#**Extra ponto**

In [ ]:
#dados['Datas'], dados['Total'] = dados['="Data de cadastro";="Total"'].str.split(';', 1).str